In [12]:
import numpy as np

## Matrix
Create a 2 by 2 augmented matrix as an ndarray object:

In [26]:
matrix_a =  np.asarray([
    [1, 3],
    [50, 2]  
], dtype=np.float32)

print(matrix)

[[ 52.   8.]
 [152.  12.]]


## Row Operations:
- Swap Rows
- Multiple Rows
- Add Rows

In [17]:
# Swap the second row (at index value 1) with the first row (at index value 0).
matrix = matrix[[1,0]]
print(matrix)
# Multipy the second row by 2.
matrix[1] = 2*matrix[1]
print(matrix)
# Add the second row to the first row.
matrix[1] = matrix[1] + matrix[0]
print(matrix)

[[52.  8.]
 [50.  2.]]
[[ 52.   8.]
 [100.   4.]]
[[ 52.   8.]
 [152.  12.]]


## Vectors
Create vectors like matrix but with only one value per row, or online one row.

In [20]:
# Create a vector
vector_one = np.asarray([
    [3],
    [0],
    [1]
], dtype=np.float32)
print(vector_one)

[[3.]
 [0.]
 [1.]]


we can use the + and the - operators to perform vector addition and subtraction. In addition, we can use the * operator to multiply a vector by a scalar quantity.

In [21]:
vector_two = 2*vector_one + 0.5*vector_one
print(vector_two)

[[7.5]
 [0. ]
 [2.5]]


**Compute Dot Product**

the columns in the first matrix need to match the number of rows in the second matrix.

In [23]:
# use np.dot(ndarry, ndarry)
vector_dp = np.dot(vector_one[:,0], vector_two)
print(vector_dp)

[25.]


## Matrix & Vector Algebra

**Multiply matrix and vectors:**

In [30]:
matrix_a =  np.asarray([
    [1, 3],
    [50, 2]  
], dtype=np.float32)

vector_b =  np.asarray([
    [6],
    [9]  
], dtype=np.float32)

#np.dot on a matrix and a vector
ab_product = np.dot(matrix_a, vector_b)
print(ab_product)

#np.dot on a matrix and another matrix
ab_product = np.dot(matrix_a, matrix_b)
print(ab_product)

[[ 33.]
 [318.]]
[[ 65.  33.]
 [290. 318.]]


**Transpose Matrix**

In [31]:
tanspose_a = np.transpose(matrix_a)
print(tanspose_a)

[[ 1. 50.]
 [ 3.  2.]]


**Create an Identify Matrix**

In [32]:
# np.identity(n)
id_matrix = np.identity(5)
print(id_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**Matrix determinant**

In [33]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004

**Matrix Inverse**

In [35]:
matrix_a = np.asarray([
    [1.5, 3],
    [1, 4]
])
inverse_a = np.linalg.inv(matrix_a)
print(inverse_a)

[[ 1.33333333 -1.        ]
 [-0.33333333  0.5       ]]


**Product of Matrix and Matrix Inverse**

Results in an identity matrix.

In [38]:
identity_matrix = np.dot(matrix_a, inverse_a)
print(identity_matrix)

[[1. 0.]
 [0. 1.]]
